name: Release multi-arch Docker Image

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - run: go version

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: public.ecr.aws
        username: ${{ secrets.TC_ACCESS_KEY }}
        password: ${{ secrets.TC_SECRET_KEY }}

    - name: go-mod verify
      run: go mod verify

    - name: go-mod tidy
      run: go mod tidy

    - name: go-build
      env:
        GOOS: linux
      run: go build

    - name: go-test
      run: go test -v ./...

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker info
      run: docker info
    - name: Buildx inspect
      run: docker buildx inspect

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        # Only push if we are publishing a release
        push: true
        tags: public.ecr.aws/r3g4e1o9/testcontainers/ryuk:${{ github.event.release.tag_name }}
